version: 0.1.{build}
pull_requests:
  do_not_increment_build_number: true
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: .\build.ps1 -Target CI
test: off
cache:
- tools -> tools\packages.config
- tools\nuget.exe -> build.ps1